### PR TITLE
new events added

### PR DESCRIPTION
**Pull request by HakanGulgen**

### CODE REVIEW

**Comment by MertUnverdi** [comment]
Emeğine sağlık

TransferEventi cancellabe yapabiliriz?

**Comment by PeachesMLG** [comment]
I think API events should be added to IridiumSkyblock instead, that way developers dont have to worry about any weird generic stuff or casting. Ill see if I have time to add these events tomorrow

**Comment by MertUnverdi** [comment]
i dont agree u with this, if we made team stuffs in IridiumSkyblock why IridiumTeams exist? U was closed my rn i'll ask again why you made IridiumTeams?? it just for testing generics?

**Comment by PeachesMLG** [comment]
Because from a developer standpoint, it will be alot easier to use the api if it sits in skyblock, then u dont have to do any casting or use any generics or anything.

Tbh, im not even sure if the Spigot Events support generics

**Pull request closed without merging**
